# Streamlit configuration

[server]
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[mapbox]
token = ""  # Add your Mapbox token here if needed

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[runner]
magicEnabled = true
installTracer = true
fixMatplotlib = true

[client]
toolbarMode = "auto"
showErrorDetails = true

[global]
developmentMode = false
dataFrameSerialization = "arrow"